version: '3'
services:
    server:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 4000:4000
        volumes:
            - dist:/app/dist

    client:
        image: nginx:latest
        container_name: client
        #build:
        #    context: .
        #    dockerfile: Dockerfile.client
        volumes:
            - dist:/usr/share/nginx/html
            - ./config/nginx.conf:/etc/nginx/conf.d/site.conf

        ports:
            - "80:80"
#            - "443:443"
        depends_on:
            - server

volumes:
    dist: