FROM node:16.13

WORKDIR /app

COPY . /app

#RUN npm install -g npm

RUN npm install -g pm2

RUN npm install

RUN npm run build-server

#RUN npm install nodemon

#CMD [ "pm2", "start", ".", "--name", "server" ]
CMD ["node", "."]
