FROM node:16.13 as build

WORKDIR /app

COPY . /app

#RUN npm install -g npm

RUN npm install

RUN npm run build-client

#RUN npm install nodemon

#CMD [ "pm2", "start", ".", "--name", "server" ]

FROM nginx:latest

COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

#WORKDIR /app

COPY --from=build /app/dist/* /usr/share/nginx/html/

EXPOSE 80