version: '3'
services:
    server:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 4000:4000
        volumes:
            - dist:/app/dist

    client:
        image: nginx:latest
        container_name: client
        volumes: 
            - dist:/app
            - ./config/default:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
#            - "443:443"

volumes:
    dist: