FROM node:16.13

WORKDIR /app

COPY . /app

#RUN npm install -g npm

RUN npm install

RUN npm run build-client

#RUN npm install nodemon

#CMD [ "pm2", "start", ".", "--name", "server" ]

FROM nginx:latest

COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./dist /usr/share/nginx/html